### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by neotigger** [lafriks/python-karcher#3]
I get the following error message:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/karcher-home", line 5, in <module>
    from karcher.cli import safe_cli
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/karcher/cli.py", line 14, in <module>
    from karcher.karcher import KarcherHome
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/karcher/karcher.py", line 21, in <module>
    from .device import Device, DeviceProperties
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/karcher/device.py", line 83, in <module>
    @dataclass(init=False)
     ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'karcher.device.DevicePropertiesNetwork'> for field net_status is not allowed: use default_factory

Please Help

**Comment by lafriks** [comment]
Problem should be fixed in v0.5.1
